In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("dataset_Facebook.csv")
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Page total likes                                                     500 non-null    int64
 1   Type                                                                 500 non-null    object
 2   Category                                                             500 non-null    int64
 3   Post Month                                                           500 non-null    int64
 4   Post Weekday                                                         500 non-null    int64
 5   Post Hour                                                            500 non-null    int64
 6   Paid                                                                 499 non-null    float64
 7   Lifetime Post Total Reach                                            500 non-null    int64
 8   Lifetime Post Total Impressions                                      500 non-null    int64
 9   Lifetime Engaged Users                                               500 non-null    int64
 10  Lifetime Post Consumers                                              500 non-null    int64
 11  Lifetime Post Consumptions                                           500 non-null    int64
 12  Lifetime Post Impressions by people who have liked your Page         500 non-null    int64
 13  Lifetime Post reach by people who like your Page                     500 non-null    int64
 14  Lifetime People who have liked your Page and engaged with your post  500 non-null    int64
 15  comment                                                              500 non-null    int64
 16  like                                                                 499 non-null    float64
 17  share                                                                496 non-null    float64
 18  Total Interactions                                                   500 non-null    int64
dtypes: float64(3), int64(15), object(1)
memory usage: 74.3+ KB

In [ ]:
df.isna().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [ ]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [ ]:
mode=df[["Paid","like","share"]].mode()
mode

   Paid  like  share
0   0.0  98.0   13.0
1   NaN   NaN   14.0

In [ ]:
df=df.fillna(mode.iloc[0])
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,0.0,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
df.isna().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   0
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   0
share                                                                  0
Total Interactions                                                     0
dtype: int64

In [ ]:
cond1=df[df["Type"]=='Photo']
cond1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,0.0,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
cond2=df[df["Post Month"]>=6]
cond2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,123047,Photo,3,6,2,13,0.0,3418,5659,581,546,770,4491,2620,327,2,51.0,6.0,59
322,123047,Photo,3,6,2,5,1.0,3662,6476,560,522,677,4930,2660,319,2,67.0,14.0,83
323,123047,Photo,3,6,1,10,0.0,56672,104966,2579,1334,1850,78678,37408,1831,20,1372.0,47.0,1439
324,123047,Photo,3,6,1,3,1.0,3294,5499,526,488,599,4658,2710,305,2,57.0,6.0,65
325,121540,Photo,3,6,1,3,0.0,3110,5405,732,712,892,4605,2540,342,2,33.0,10.0,45

In [ ]:
cond3=df[df["Post Month"]<6]
cond3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
326,121540,Photo,2,5,7,14,0.000000,3806,6486,722,658,880,4955,2772,361,1,79.0,17.0,97
327,120050,Photo,3,5,5,9,1.000000,3776,6736,577,529,719,4846,2614,371,3,97.0,22.0,122
328,120050,Photo,3,5,4,12,0.000000,39040,55633,1684,1183,2123,32021,19712,1101,16,617.0,58.0,691
329,120050,Photo,3,5,4,4,1.000000,4032,7278,684,607,848,4935,2644,432,7,139.0,34.0,180
330,120050,Photo,3,5,3,12,0.000000,21248,34095,1049,918,1438,11280,6664,536,20,199.0,32.0,251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.000000,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.000000,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.000000,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.000000,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,0.278557,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
cond4=df[(df["Type"]=="Photo") &(df["Category"]==2)]
cond4

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.000000,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
3,139441,Photo,2,12,2,10,1.000000,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.000000,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
11,139441,Photo,2,12,5,10,0.000000,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.000000,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,91758,Photo,2,2,5,3,1.000000,15880,51571,1188,1071,1410,47976,13560,677,1,200.0,37.0,238
480,86909,Photo,2,1,4,11,0.000000,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
483,86491,Photo,2,1,3,3,0.000000,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
496,81370,Photo,2,1,5,8,0.000000,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
499,81370,Photo,2,1,4,4,0.278557,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
cond5=df.head(100)
cond5

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,137059,Photo,3,10,6,10,0.0,3090,5744,391,257,360,3521,1796,293,5,153.0,27.0,185
96,137059,Photo,1,10,6,3,0.0,1101,2548,324,287,2418,1284,704,220,3,51.0,11.0,65
97,137059,Photo,2,10,5,11,0.0,2819,5230,318,218,303,3128,1622,240,1,115.0,26.0,142
98,137020,Status,2,10,5,3,1.0,12468,24917,2143,1966,2576,15850,7636,1661,7,310.0,61.0,378
99,137020,Photo,1,10,4,10,0.0,12776,21893,785,539,881,13272,7800,575,12,328.0,90.0,430

In [ ]:
cond6=df.tail(100)
cond6

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
400,107907,Photo,3,4,4,5,1.0,3714,6385,537,481,645,4441,2512,395,5,91.0,26.0,122
401,107907,Photo,1,4,3,13,1.0,46192,80227,1364,1096,1697,32842,16960,762,9,329.0,38.0,376
402,107907,Photo,1,4,3,4,1.0,39568,47128,741,652,957,22022,16096,519,4,128.0,17.0,149
403,107907,Link,1,4,2,6,0.0,70912,94172,1374,1106,1267,42338,27232,788,1,379.0,40.0,420
404,107907,Photo,3,4,1,3,0.0,4552,7253,471,444,569,4440,2664,316,1,52.0,24.0,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,0.0,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
cond7=df[0:500:5]
cond7

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,86909,Photo,3,1,6,16,1.0,5754,9238,1179,1143,1452,6101,3546,420,0,65.0,19.0,84
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
490,85979,Photo,3,1,6,11,0.0,5280,8703,951,911,1237,5757,3300,431,1,79.0,30.0,110
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84

In [ ]:
cond8=df.iloc[0:300,3:7]
cond8

     Post Month  Post Weekday  Post Hour  Paid
0            12             4          3   0.0
1            12             3         10   0.0
2            12             3          3   0.0
3            12             2         10   1.0
4            12             2          3   0.0
..          ...           ...        ...   ...
295           6             2          2   0.0
296           6             1         14   0.0
297           6             1          3   0.0
298           6             7         11   0.0
299           6             7          4   0.0

[300 rows x 4 columns]

In [ ]:
cond9=df[["Type","Category","Post Month","Post Weekday","Post Hour"]]
cond9

       Type  Category  Post Month  Post Weekday  Post Hour
0     Photo         2          12             4          3
1    Status         2          12             3         10
2     Photo         3          12             3          3
3     Photo         2          12             2         10
4     Photo         2          12             2          3
..      ...       ...         ...           ...        ...
495   Photo         3           1             7          2
496   Photo         2           1             5          8
497   Photo         1           1             5          2
498   Photo         3           1             4         11
499   Photo         2           1             4          4

[500 rows x 5 columns]

In [ ]:
cond10=df[["Type","comment","like","share"]]
cond10

       Type  comment    like  share
0     Photo        4    79.0   17.0
1    Status        5   130.0   29.0
2     Photo        0    66.0   14.0
3     Photo       58  1572.0  147.0
4     Photo       19   325.0   49.0
..      ...      ...     ...    ...
495   Photo        5    53.0   26.0
496   Photo        0    53.0   22.0
497   Photo        4    93.0   18.0
498   Photo        7    91.0   38.0
499   Photo        0    91.0   28.0

[500 rows x 4 columns]

In [ ]:
cond11=pd.concat([cond5,cond6],axis=0)
cond11

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,0.0,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
cond15=pd.concat([cond9,cond10],axis=1)
cond15

,Type,Category,Post Month,Post Weekday,Post Hour,Type,comment,like,share
0,Photo,2,12,4,3,Photo,4,79.0,17.0
1,Status,2,12,3,10,Status,5,130.0,29.0
2,Photo,3,12,3,3,Photo,0,66.0,14.0
3,Photo,2,12,2,10,Photo,58,1572.0,147.0
4,Photo,2,12,2,3,Photo,19,325.0,49.0
...,...,...,...,...,...,...,...,...,...
495,Photo,3,1,7,2,Photo,5,53.0,26.0
496,Photo,2,1,5,8,Photo,0,53.0,22.0
497,Photo,1,1,5,2,Photo,4,93.0,18.0
498,Photo,3,1,4,11,Photo,7,91.0,38.0
499,Photo,2,1,4,4,Photo,0,91.0,28.0

In [ ]:
cond12=cond9.merge(cond10,on="Type")
cond12

,Type,Category,Post Month,Post Weekday,Post Hour,comment,like,share
0,Photo,2,12,4,3,4,79.0,17.0
1,Photo,2,12,4,3,0,66.0,14.0
2,Photo,2,12,4,3,58,1572.0,147.0
3,Photo,2,12,4,3,19,325.0,49.0
4,Photo,2,12,4,3,3,249.0,27.0
...,...,...,...,...,...,...,...,...
184029,Photo,2,1,4,4,5,53.0,26.0
184030,Photo,2,1,4,4,0,53.0,22.0
184031,Photo,2,1,4,4,4,93.0,18.0
184032,Photo,2,1,4,4,7,91.0,38.0
184033,Photo,2,1,4,4,0,91.0,28.0

In [ ]:
cond13=df.T
cond13

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [ ]:
df['Category'].value_counts()

Category
1    215
3    155
2    130
Name: count, dtype: int64

In [ ]:
cond14 = df.groupby(["Paid", "like", "share"]).agg("sum")
cond14

                   Page total likes             Type  Category  Post Month  \
Paid like   share
0.0  0.0    0.0              380377  PhotoPhotoPhoto         3          26
     1.0    2.0              136393            Photo         1          10
     2.0    0.0              202844       PhotoPhoto         2           6
            13.0             136393            Photo         1          10
     3.0    0.0              237125       PhotoPhoto         2          13
...                             ...              ...       ...         ...
1.0  859.0  90.0             136013           Status         2          10
     1047.0 98.0             135195            Photo         3           9
     1572.0 147.0            139441            Photo         2          12
     1998.0 128.0            111620            Photo         3           4
     5172.0 790.0            130791            Photo         2           7

                   Post Weekday  Post Hour  Lifetime Post Total Reach  \
Paid like   share
0.0  0.0    0.0              13         22                       4486
     1.0    2.0               7          8                        619
     2.0    0.0               8         34                       5370
            13.0              7          9                        584
     3.0    0.0              13         27                       4526
...                         ...        ...                        ...
1.0  859.0  90.0              3          2                      31136
     1047.0 98.0              6          3                      22304
     1572.0 147.0             2         10                      50128
     1998.0 128.0             1         14                     105632
     5172.0 790.0             3          5                     180480

                   Lifetime Post Total Impressions  Lifetime Engaged Users  \
Paid like   share
0.0  0.0    0.0                               7333                      57
     1.0    2.0                               1096                     257
     2.0    0.0                               9637                     541
            13.0                              1029                     273
     3.0    0.0                               8481                     350
...                                            ...                     ...
1.0  859.0  90.0                             59964                    6164
     1047.0 98.0                             37159                    1805
     1572.0 147.0                            87991                    2211
     1998.0 128.0                           147918                    3984
     5172.0 790.0                           319133                    8072

                   Lifetime Post Consumers  Lifetime Post Consumptions  \
Paid like   share
0.0  0.0    0.0                         57                          70
     1.0    2.0                        254                         292
     2.0    0.0                        540                        2524
            13.0                       271                         308
     3.0    0.0                        349                        1285
...                                    ...                         ...
1.0  859.0  90.0                      5934                        9237
     1047.0 98.0                       984                        1618
     1572.0 147.0                      790                        1119
     1998.0 128.0                     2254                        3391
     5172.0 790.0                     4010                        6242

                   Lifetime Post Impressions by people who have liked your Page  \
Paid like   share
0.0  0.0    0.0                                                 6071
     1.0    2.0                                                  951
     2.0    0.0                                                 9632
            13.0                                                 943
     3.0    0.0                                                 8362
...                                                              ...
1.0  859.0  90.0                                               35977
     1047.0 98.0                                               22864
     1572.0 147.0                                              61027
     1998.0 128.0                                              48575
     5172.0 790.0                                             108752

                   Lifetime Post reach by people who like your Page  \
Paid like   share
0.0  0.0    0.0                                                3462
     1.0    2.0                                                 516
     2.0    0.0                                                5368
            13.0                                                511
     3.0    0.0                                                4448
...                                                             ...
1.0  859.0  90.0                                              18048
     1047.0 98.0                                              13304
     1572.0 147.0                                             32048
     1998.0 128.0                                             27328
     5172.0 790.0                                             51456

                   Lifetime People who have liked your Page and engaged with your post  \
Paid like   share
0.0  0.0    0.0                                                   47
     1.0    2.0                                                  217
     2.0    0.0                                                  492
            13.0                                                 232
     3.0    0.0                                                  315
...                                                              ...
1.0  859.0  90.0                                                4376
     1047.0 98.0                                                1349
     1572.0 147.0                                               1386
     1998.0 128.0                                               1936
     5172.0 790.0                                               3316

                   comment  Total Interactions
Paid like   share
0.0  0.0    0.0          0                   0
     1.0    2.0          1                   4
     2.0    0.0          0                   4
            13.0         0                   2
     3.0    0.0          0                   6
...                    ...                 ...
1.0  859.0  90.0        60                1009
     1047.0 98.0        29                1174
     1572.0 147.0       58                1777
     1998.0 128.0       51                2177
     5172.0 790.0      372                6334

[476 rows x 16 columns]